sudo: false

language: python

matrix:
  include:
    - python: "2.7"
        addons:
          apt:
            packages:
            - python-numpy 
            - python-scipy 
    - python: "3.2"
        addons:
          apt:
            packages:
            - python3-numpy 
            - python3-scipy 
            
virtualenv:
    system_site_packages: true

install:
  - python setup.py install

script:  
  - pwd
  - nosetests -vs

