
sudo: false

addons:
  apt:
    packages:
    - python-numpy 
    - python-scipy 
    - nose
    
language: python

python: 2.7

virtualenv:
    system_site_packages: true

install:
  - python setup.py install

# command to run tests
script:  
  - pwd
  - nosetests -vs

