language: python

python:
  - "2.6"
  - "2.7"
#  - "3.2"

virtualenv:
  system_site_packages: true

# command to install dependencies
install:
  - "sudo apt-get install -qq python-numpy python-scipy"
  - "python setup.py"

# command to run tests and examples, e.g. python setup.py test
script:  
  - pwd

