sudo: false

addons:
  apt:
    packages:
    - python-numpy 
    - python-scipy 
    
language: python

python: 
  - "2.7"
  - "3.4"

virtualenv:
    system_site_packages: true

install:

  - pip install scipy # Why needed again?
  - python setup.py install

script:  
  - pwd
  - nosetests -vs

