language: python

python:
  - "2.7_with_system_site_packages"
#  - "3.2"

before_install:
  - sudo apt-get update -qq
  - pip install numpy
  - pip install scipy
  - pip install nose

install:
  - "python setup.py install"

# command to run tests
script:  
  - pwd
  - nosetests -vs

