language: python

python:
  - "2.6"
  - "2.7"
#  - "3.2"

before_install:
- sudo apt-get update -qq
- pip install numpy

install:
  - "python setup.py"

# command to run tests and examples, e.g. python setup.py test
script:  
  - pwd

