language: python

python:
  - "2.6"
  - "2.7"
#  - "3.2"


# command to install dependencies
install:
  - "pip install scipy"
  - "pip install matplotlib"
  - "python setup.py"

# command to run tests and examples, e.g. python setup.py test
script:  
  - pwd

