sudo: false

addons:
  apt:
    packages:
    - python-numpy 
    - python-scipy 
    
language: python

python: 
  - "2.6"
  - "2.7"
  - "3.2"

virtualenv:
    system_site_packages: true

install:
  - python setup.py install

script:  
  - pwd
  - nosetests -vs

