sudo: false

addons:
  apt:
    packages:
    - python-numpy 
    - python-scipy 
    # Quick fix, requires matrix for addons...
    - python3-numpy 
    - python3-scipy 
    
language: python

python: 
  - "2.7"
  - "3.4"

virtualenv:
    system_site_packages: true

install:
  - python setup.py install

script:  
  - pwd
  - nosetests -vs

